# ===================================================================
#                   Database configuration
# ===================================================================

spring:
  datasource:
    initialize: false
    driver-class-name: org.postgresql.Driver
