version: "2"
services:
  tel-person-service:
    image: tel-person-backend-service:1.0.0-SNAPSHOT
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,address=8000,suspend=n,server=y
    ports:
      - "8080"
      - "8000"
